### ISSUE TITLE
Redcarpet Markdown

### ISSUE THREAD

**Issue by Golpha** [wwphp-fb/wwphp-fb.github.io#17]
Due to the upgrade of jekyll to version 3.0 on github, it will no longer possible to use redcarpet after May 1st, 2016.

See: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

All repositories that make use of jekyll must be fixed until May 1st, 2016.

**Comment by peterkokot** [comment]
:+1: Currently I don't recall exactly why the redcarpet has been even used in the first place. I think it was because it didn't have some issues with highlighting code and mixing MarkDown HTML at the same time. I'm on it. Update to Jekyll 3.0 is great since it has a lot of goodies.

**Comment by peterkokot** [comment]
Closing via 865f8faec081c20f0b5908c3f580301581fe215c
