### ISSUE TITLE
List of PHP Podcasts

### ISSUE THREAD

**Issue by RCMainak** [wwphp-fb/wwphp-fb.github.io#26]
Let's make a page listing all the good PHP podcasts.

@peterkokot have shared a list of podcast with me already on fb group. the list can be found below if you have any suggestions please feel free to comment here or create a PR.

PHP ones:
* https://www.phproundtable.com/
* https://www.phppodcasts.com/
* https://phptownhall.com/

There are also frameworks specific ones:
* http://www.soundofsymfony.com/
* http://www.laravelpodcast.com/

**Comment by peterkokot** [comment]
:+1: Sounds good to me. It will be added here:
https://github.com/wwphp-fb/php-resources

**Comment by peterkokot** [comment]
PHP Podcasts chapter added via eec51bfb8ab7ecf2e726fb923fcf4d29e37ce7ab

In case there is some missing, let me know.

**Comment by RCMainak** [comment]
looks nice. I'll ask people around to see if I can find more good podcasts :smiley:
